sudo: false
language: go
# handle submodules ourselves
git:
  submodules: false
go:
  - 1.6.x
  - 1.7.x
  - 1.8
  - tip
before_install:
   #these two lines help users who fork mesos-go. It's a noop when running from the mesos organization
  - RepoName=`basename $PWD`; SrcDir=`dirname $PWD`; DestDir="`dirname $SrcDir`/mesos"
  - if [[ "$SrcDir" != "$DestDir" ]]; then mv "$SrcDir" "$DestDir"; cd ../../mesos/$RepoName; export TRAVIS_BUILD_DIR=`dirname $TRAVIS_BUILD_DIR`/$RepoName; fi
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - go get github.com/mattn/goveralls
install:
  - make install
script:
  - rm -rf $HOME/gopath/pkg && make coverage && $HOME/gopath/bin/goveralls -service=travis-ci -coverprofile=_output/coverage.out
