sudo: false
language: go
# handle submodules ourselves
git:
  submodules: false
go:
  - 1.7.x
  - 1.8
before_install:
   #these two lines help users who fork mesos-go. It's a noop when running from the mesos organization
  - RepoName=`basename $PWD`; SrcDir=`dirname $PWD`; DestDir="`dirname $SrcDir`/mesos"
  - if [[ "$SrcDir" != "$DestDir" ]]; then mv "$SrcDir" "$DestDir"; cd ../../mesos/$RepoName; export TRAVIS_BUILD_DIR=`dirname $TRAVIS_BUILD_DIR`/$RepoName; fi
  - go get github.com/mattn/goveralls
  - go get github.com/kardianos/govendor
  - make sync
install:
  - make test install
script:
  - if [[ "$TRAVIS_EVENT_TYPE" = "pull_request" ]]; then make coveralls; fi
