sudo: false
language: go
# handle submodules ourselves
git:
  submodules: false
go:
  - 1.6.x
  - 1.7.x
  - 1.8
before_install:
   #these two lines help users who fork mesos-go. It's a noop when running from the mesos organization
  - RepoName=`basename $PWD`; SrcDir=`dirname $PWD`; DestDir="`dirname $SrcDir`/mesos"
  - if [[ "$SrcDir" != "$DestDir" ]]; then mv "$SrcDir" "$DestDir"; cd ../../mesos/$RepoName; export TRAVIS_BUILD_DIR=`dirname $TRAVIS_BUILD_DIR`/$RepoName; fi
  - go get github.com/mattn/goveralls
  - go get github.com/kardianos/govendor
  - make sync
install:
  - make install
script:
  - rm -rf $HOME/gopath/pkg && make coverage && $HOME/gopath/bin/goveralls -service=travis-ci -coverprofile=_output/coverage.out -ignore=$((tr '\n' , | sed -e 's/$,//g') < <(find api/v1/cmd -type f -name '*.go'|grep -v -e /vendor/ ; ls api/v1/lib{,/scheduler,/executor}/*.pb{,_ffjson}.go ; find api/v0 -type d))
