// DO NOT EDIT!
// Code generated by ffjson <https://github.com/pquerna/ffjson>
// DO NOT EDIT!

package main

import (
	importedinceptionpackage "github.com/mesos/mesos-go/tests/int64support"
	"github.com/pquerna/ffjson/inception"
)

func main() {
	i := ffjsoninception.NewInception("demo.pb.go", "mesos", "demo.pb_ffjson.go", false)
	i.AddMany(importedinceptionpackage.FFJSONExpose())
	i.Execute()
}
