// Code generated by protoc-gen-gogo.
// source: fetcher.proto
// DO NOT EDIT!

package mesosproto

import proto "github.com/gogo/protobuf/proto"
import math "math"

// discarding unused import gogoproto "github.com/gogo/protobuf/gogoproto/gogo.pb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

// *
// Encodes the fetcher environment variable sent to the external fetcher
// program.
type FetcherInfo struct {
	CommandInfo      *CommandInfo `protobuf:"bytes,1,req,name=command_info" json:"command_info,omitempty"`
	WorkDirectory    *string      `protobuf:"bytes,2,req,name=work_directory" json:"work_directory,omitempty"`
	User             *string      `protobuf:"bytes,3,opt,name=user" json:"user,omitempty"`
	FrameworksHome   *string      `protobuf:"bytes,4,opt,name=frameworks_home" json:"frameworks_home,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *FetcherInfo) Reset()         { *m = FetcherInfo{} }
func (m *FetcherInfo) String() string { return proto.CompactTextString(m) }
func (*FetcherInfo) ProtoMessage()    {}

func (m *FetcherInfo) GetCommandInfo() *CommandInfo {
	if m != nil {
		return m.CommandInfo
	}
	return nil
}

func (m *FetcherInfo) GetWorkDirectory() string {
	if m != nil && m.WorkDirectory != nil {
		return *m.WorkDirectory
	}
	return ""
}

func (m *FetcherInfo) GetUser() string {
	if m != nil && m.User != nil {
		return *m.User
	}
	return ""
}

func (m *FetcherInfo) GetFrameworksHome() string {
	if m != nil && m.FrameworksHome != nil {
		return *m.FrameworksHome
	}
	return ""
}

func init() {
}
