// Code generated by protoc-gen-go.
// source: registry.proto
// DO NOT EDIT!

package mesos_internal_registry

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"
import mesos "mesos.pb"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Slave struct {
	Info             *mesos.SlaveInfo `protobuf:"bytes,2,req,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *Slave) Reset()         { *m = Slave{} }
func (m *Slave) String() string { return proto.CompactTextString(m) }
func (*Slave) ProtoMessage()    {}

func (m *Slave) GetInfo() *mesos.SlaveInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type Slaves struct {
	Slaves           []*Slave `protobuf:"bytes,1,rep,name=slaves" json:"slaves,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Slaves) Reset()         { *m = Slaves{} }
func (m *Slaves) String() string { return proto.CompactTextString(m) }
func (*Slaves) ProtoMessage()    {}

func (m *Slaves) GetSlaves() []*Slave {
	if m != nil {
		return m.Slaves
	}
	return nil
}

func init() {
}
